spring.application.name=catalogoroupas
spring.datasource.url=jdbc:mysql://localhost:3306/ramis_cliente?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@nder03Sql

spring.jpa.show-sql=false
spring.mvc.hiddenmethod.filter.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.cache=false
server.port=8083